name: Deploy for private repository

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Git Submodule Status Commenter
        uses: rematocorp/submodule-status-commenter@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in deploy directory
        run: ls deploy
      - name: List files
        run: ls