name: Deploy for private repository

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.PAT_TOKEN  }}
          submodules: recursive
          fetch-depth: 0
          set-safe-directory: true
      - name: Update git submodules
        run: git submodule update --remote --recursive
      - name: List files in deploy directory
        run: ls deploy
      - name: List files
        run: ls